"""Request/Response models for Verify API."""
from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime
import uuid


class VerifyTextRequest(BaseModel):
    """Request model for text verification."""
    
    text: str = Field(
        ...,
        min_length=10,
        description="Text content to analyze (minimum 10 characters)"
    )
    return_signals: bool = Field(
        default=True,
        description="Whether to return detailed detection signals"
    )
    model_version: Optional[str] = Field(
        default="latest",
        description="Model version to use for analysis"
    )


class DetectionSignal(BaseModel):
    """A single detection signal from the analysis."""
    
    name: str = Field(description="Signal name (e.g., perplexity, burstiness)")
    value: float = Field(description="Signal value (0.0 to 1.0 normalized)")
    description: str = Field(description="Human-readable description of the signal")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "perplexity",
                "value": 0.92,
                "description": "Low text complexity indicating potential AI generation"
            }
        }
    }


class VerifyTextResponse(BaseModel):
    """Response model for text verification."""
    
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique verification ID"
    )
    ai_probability: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Probability that the text was generated by AI (0.0 to 1.0)"
    )
    confidence: Literal["low", "medium", "high"] = Field(
        ...,
        description="Confidence level of the prediction"
    )
    signals: Optional[List[DetectionSignal]] = Field(
        default=None,
        description="Detailed detection signals (only included if return_signals=true)"
    )
    model_version: str = Field(
        description="Version of the detection model used"
    )
    processing_time_ms: int = Field(
        description="Processing time in milliseconds"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of the verification"
    )
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "ai_probability": 0.85,
                "confidence": "high",
                "signals": [
                    {
                        "name": "perplexity",
                        "value": 0.92,
                        "description": "Low text complexity"
                    },
                    {
                        "name": "burstiness",
                        "value": 0.15,
                        "description": "Uniform sentence length"
                    }
                ],
                "model_version": "v0.1.0",
                "processing_time_ms": 234,
                "created_at": "2025-01-14T12:00:00Z"
            }
        }
    }


class BatchVerifyRequest(BaseModel):
    """Request model for batch text verification."""
    
    texts: List[str] = Field(
        ...,
        min_length=1,
        max_length=100,
        description="List of text contents to analyze"
    )
    return_signals: bool = Field(
        default=False,
        description="Whether to return detailed detection signals"
    )


class BatchVerifyResponse(BaseModel):
    """Response model for batch text verification."""
    
    batch_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique batch verification ID"
    )
    results: List[VerifyTextResponse] = Field(
        description="Individual verification results"
    )
    total_count: int = Field(
        description="Total number of texts processed"
    )
    processing_time_ms: int = Field(
        description="Total batch processing time in milliseconds"
    )


class ErrorResponse(BaseModel):
    """Standard error response."""
    
    error: str = Field(description="Error type code")
    message: str = Field(description="Human-readable error message")
    detail: Optional[str] = Field(
        default=None,
        description="Additional error details"
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Request ID for debugging"
    )


class HealthResponse(BaseModel):
    """Health check response."""
    
    status: Literal["healthy", "degraded", "unhealthy"]
    version: str
    timestamp: datetime
    services: dict = Field(
        default_factory=dict,
        description="Status of dependent services"
    )
