"""Text verification API endpoints."""
import time
import json
from fastapi import APIRouter, Depends, HTTPException, status, Request
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import verify_api_key
from app.db import get_db, APIKey, UsageLog, VerificationResult
from app.services.api_key_service import api_key_service
from app.services.rate_limiter import rate_limiter
from app.models.schemas import (
    VerifyTextRequest,
    VerifyTextResponse,
    BatchVerifyRequest,
    BatchVerifyResponse,
    ErrorResponse,
)
from app.services.text_analyzer import analyze_text

router = APIRouter(prefix="/verify", tags=["verification"])


async def verify_key_and_check_rate(
    request: Request,
    api_key_str: str = Depends(verify_api_key),
    db: AsyncSession = Depends(get_db),
) -> APIKey:
    """
    Verify API key and check rate limits.
    
    This dependency verifies the key and enforces rate limiting.
    """
    # Verify the key
    api_key = await api_key_service.verify_key(db, api_key_str)
    
    if not api_key:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or revoked API key"
        )
    
    # Check rate limit
    allowed, remaining, reset_time = await rate_limiter.check_rate_limit(
        str(api_key.id),
        api_key.rate_limit_tier
    )
    
    if not allowed:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail=f"Rate limit exceeded. Limit resets at {reset_time}",
            headers={
                "X-RateLimit-Limit": str(api_key_service.get_rate_limit(api_key.rate_limit_tier)[0]),
                "X-RateLimit-Remaining": "0",
                "X-RateLimit-Reset": str(reset_time),
            }
        )
    
    # Add rate limit headers to request state for logging
    request.state.rate_limit_remaining = remaining
    
    return api_key


@router.post(
    "/text",
    response_model=VerifyTextResponse,
    responses={
        400: {"model": ErrorResponse},
        401: {"model": ErrorResponse},
        429: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
    summary="Verify if text is AI-generated",
    description="Analyzes text content to determine the probability it was generated by AI. "
                "Uses perplexity and burstiness analysis to detect common AI writing patterns.",
)
async def verify_text(
    request_body: VerifyTextRequest,
    http_request: Request,
    api_key: APIKey = Depends(verify_key_and_check_rate),
    db: AsyncSession = Depends(get_db),
) -> VerifyTextResponse:
    """
    Verify text content for AI generation.
    
    - **text**: The text content to analyze (minimum 10 characters)
    - **return_signals**: Whether to include detailed detection signals in response
    - **model_version**: Which model version to use (default: latest)
    
    Returns AI probability (0.0-1.0), confidence level, and optional signals.
    """
    start_time = time.time()
    error_message = None
    
    try:
        # Validate input
        if len(request_body.text.strip()) < 10:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Text must be at least 10 characters after trimming whitespace."
            )
        
        # Perform analysis
        analysis_result = analyze_text(request_body.text)
        
        # Calculate processing time
        processing_time_ms = int((time.time() - start_time) * 1000)
        
        # Build response
        response = VerifyTextResponse(
            id=analysis_result.get("id", ""),
            ai_probability=analysis_result["ai_probability"],
            confidence=analysis_result["confidence"],
            signals=analysis_result.get("signals") if request_body.return_signals else None,
            model_version="v0.1.0",
            processing_time_ms=processing_time_ms,
        )
        
        # Store verification result
        try:
            signals_json = json.dumps(analysis_result.get("signals", [])) if request_body.return_signals else None
            verification = VerificationResult(
                api_key_id=api_key.id,
                text_length=len(request_body.text),
                ai_probability=str(analysis_result["ai_probability"]),
                confidence=analysis_result["confidence"],
                model_version="v0.1.0",
                processing_time_ms=processing_time_ms,
                signals=signals_json,
            )
            db.add(verification)
            await db.commit()
        except Exception:
            # Don't fail the request if logging fails
            await db.rollback()
        
        return response
        
    except HTTPException:
        raise
    except Exception as e:
        error_message = str(e)
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Text verification failed: {str(e)}"
        )
    finally:
        # Log usage
        try:
            log_entry = UsageLog(
                api_key_id=api_key.id,
                endpoint="/v1/verify/text",
                method="POST",
                status_code=200 if not error_message else 500,
                response_time_ms=int((time.time() - start_time) * 1000),
                error_message=error_message,
            )
            db.add(log_entry)
            await db.commit()
        except Exception:
            await db.rollback()  # Don't fail request if logging fails


@router.post(
    "/batch",
    response_model=BatchVerifyResponse,
    responses={
        400: {"model": ErrorResponse},
        401: {"model": ErrorResponse},
        429: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
    summary="Batch verify multiple texts",
    description="Process multiple text samples in a single request for efficiency.",
)
async def verify_batch(
    request_body: BatchVerifyRequest,
    api_key: APIKey = Depends(verify_key_and_check_rate),
    db: AsyncSession = Depends(get_db),
) -> BatchVerifyResponse:
    """
    Batch verify multiple text samples.
    
    - **texts**: List of text contents to analyze (1-100 items)
    - **return_signals**: Whether to include detailed signals in each result
    
    Returns individual results for each text in the batch.
    """
    start_time = time.time()
    
    try:
        if not request_body.texts:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one text is required."
            )
        
        if len(request_body.texts) > 100:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Maximum 100 texts per batch request."
            )
        
        results = []
        
        for text in request_body.texts:
            if len(text.strip()) >= 10:
                analysis = analyze_text(text)
                results.append(
                    VerifyTextResponse(
                        id=analysis.get("id", ""),
                        ai_probability=analysis["ai_probability"],
                        confidence=analysis["confidence"],
                        signals=analysis.get("signals") if request_body.return_signals else None,
                        model_version="v0.1.0",
                        processing_time_ms=0,
                    )
                )
        
        processing_time_ms = int((time.time() - start_time) * 1000)
        
        return BatchVerifyResponse(
            batch_id="",
            results=results,
            total_count=len(results),
            processing_time_ms=processing_time_ms,
        )
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Batch verification failed: {str(e)}"
        )